[project]
description = "A Flask-based server for the CardIndex web application."
name = "cardindex-flask"
readme = "README.md"
requires-python = ">=3.14"
version = "0.1.0"

dependencies = [
    "flask>=3.1.3",
    "psycopg>=3.3.4",
    "psycopg-binary>=3.3.4",
    "python-dotenv>=1.2.2",
    "werkzeug>=3.1.8",
]

[dependency-groups]
dev = [
    "flask-migrate>=4.1.0",
    "flask-sqlalchemy>=3.1.1",
    "invoke>=3.0.3",
    "pytest>=9.1.1",
    "sqlalchemy>=2.0.51",
    "ty>=0.0.66",
]
