"""

Revision ID: 822cae9b5950
Revises: d9f59016268d
Create Date: 2026-08-01 18:04:29.902235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822cae9b5950'
down_revision = 'd9f59016268d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_cards')
    # ### end Alembic commands ###
