"""empty message

Revision ID: 824db8cab759
Revises: eb46e224037d
Create Date: 2026-08-03 16:30:28.763864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824db8cab759'
down_revision = 'eb46e224037d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
