"""

Revision ID: 8840685391a1
Revises: c7efaf437695
Create Date: 2026-08-01 18:00:43.971756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8840685391a1'
down_revision = 'c7efaf437695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
