"""empty message

Revision ID: b23cf8537806
Revises: 824db8cab759
Create Date: 2026-08-04 17:04:18.696477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23cf8537806'
down_revision = '824db8cab759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_desc'), ['desc'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_title'))
        batch_op.drop_index(batch_op.f('ix_cards_id'))
        batch_op.drop_index(batch_op.f('ix_cards_desc'))

    # ### end Alembic commands ###
